title: 'UCSF Wynton HPC Cluster'
theme: jekyll-theme-minimal

google_analytics: UA-128646955-1

organization:
  name: "Wynton"
  url: "https://wynton.ucsf.edu/"

cluster:
  name: "Wynton HPC"
  nickname: "Wynton"
  version: "1.0"
  email_support: support@wynton.ucsf.edu
  email_storage: storage@wynton.ucsf.edu
  
login:
  name: "log2"
  hostname: "log2.wynton.ucsf.edu"
  ip: "169.230.134.15"
devel:
  name: "dev3"
  hostname: "dev3"
  ip: "172.26.32.8"
transfer:
  name: "dt2"
  hostname: "dt2.wynton.ucsf.edu"
  ip: "172.26.1.17"

login1:
  name: "log1"
  hostname: "log1.wynton.ucsf.edu"
  ip: "169.230.126.77"
login2:
  name: "log2"
  hostname: "log2.wynton.ucsf.edu"
  ip: "169.230.134.15"
dev1:
  name: "dev1"
  hostname: "dev1"
  ip: "172.26.32.2"
dev2:
  name: "dev2"
  hostname: "dev2"
  ip: "172.26.32.7"
dev3:
  name: "dev3"
  hostname: "dev3"
  ip: "172.26.32.8"
gpudev1:
  name: "gpudev1"
  hostname: "gpudev1"
  ip: "172.26.32.3"
transfer1:
  name: "dt1"
  hostname: "dt1.wynton.ucsf.edu"
  ip: "169.230.126.58"
transfer2:
  name: "dt2"
  hostname: "dt2.wynton.ucsf.edu"
  ip: "172.26.1.17"

globus:
  name: "UCSF Wynton HPC"
  uuid: 1dd9beaa-14b7-11eb-abe2-0213fe609573

assets:
  status_root_path: "https://raw.githubusercontent.com/UCSF-HPC/wynton-slash/master/wynton/docs"

plugins:
  - jekyll-target-blank
