title: 'UCSF Wynton HPC Cluster'
theme: jekyll-theme-minimal

organization:
  name: "Wynton"
  url: "https://wynton.ucsf.edu/"

user:
  name: "alice"
  email: "alice.aliceson@ucsf.edu"
  home: "/wynton/home/boblab/alice"
  labfolder: "/wynton/group/boblab"
  
cluster:
  name: "Wynton HPC"
  nickname: "Wynton"
  version: "1.1"
  domain: wynton.ucsf.edu
  email_support: support@wynton.ucsf.edu
  email_storage: storage@wynton.ucsf.edu
  email_compute: compute@wynton.ucsf.edu
  email_password: password@wynton.ucsf.edu

path:
  global_root: /wynton
  global_scratch: /wynton/scratch
  cbi_software: /wynton/home/cbi/shared/software
  
login:
  name: "log1"
  hostname: "log1.wynton.ucsf.edu"
  ip: "169.230.79.44"

devel:
  name: "dev1"
  hostname: "dev1.wynton.ucsf.edu"
  ip: "172.26.44.131"

transfer:
  name: "dt1"
  hostname: "dt1.wynton.ucsf.edu"
  ip: "169.230.79.35"

login1:
  name: "log1"
  hostname: "log1.wynton.ucsf.edu"
  ip: "169.230.79.44"
login2:
  name: "log2"
  hostname: "log2.wynton.ucsf.edu"
  ip: "169.230.79.47"
dev1:
  name: "dev1"
  hostname: "dev1.wynton.ucsf.edu"
  ip: "172.26.44.131"
dev2:
  name: "dev2"
  hostname: "dev2.wynton.ucsf.edu"
  ip: "172.26.44.132"
dev3:
  name: "dev3"
  hostname: "dev3.wynton.ucsf.edu"
  ip: "172.26.44.133"
gpudev1:
  name: "gpudev1"
  hostname: "gpudev1.wynton.ucsf.edu"
  ip: "172.26.44.141"
transfer1:
  name: "dt1"
  hostname: "dt1.wynton.ucsf.edu"
  ip: "169.230.79.35"
transfer2:
  name: "dt2"
  hostname: "dt2.wynton.ucsf.edu"
  ip: "169.230.79.16"

globus:
  name: "UCSF Wynton HPC"
  uuid: 68f06816-cd00-4bf3-ae1f-0597a07ed118
globus-phi:
  name: "UCSF Wynton PDT"
  uuid: ef126934-6f8a-4af8-81cd-d5b0b7afe51f
globus-box:
  name: "UCSF Wynton HPC Box"
  uuid: 98d778c4-75a9-4d8d-8baa-68f71d6568c0

events:
  downtime: 2024-10-14T08:00:00-0700
  
assets:
  status_root_path: "https://raw.githubusercontent.com/UCSF-HPC/wynton-slash/master/wynton/docs"

plugins:
  - jekyll-target-blank

docsearch:
  api_key: c91e1057e3e3989f56b0b30ba5ea8a0b
  index_name: hpc

google_analytics: UA-128646955-1
