on: [push, pull_request]

name: 'Spell check'

jobs:
  spelling:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-22.04, r: 'latest', cran: "https://demo.rstudiopm.com/all/__linux__/jammy/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
      
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install R package 'remotes'
        run: |
          install.packages("remotes")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-spelling
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-

      - name: Install R packages
        run: |
          remotes::install_cran("spelling")
        shell: Rscript {0}

      - name: Spell check README and Markdown files
        run: |
          make spelling
